DROP TABLE IF EXISTS games;
CREATE TABLE games (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_num INT NOT NULL
)

DROP TABLE IF EXISTS results;
CREATE TABLE results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INT NOT NULL,
    user_name STRING NOT NULL,
    SCORE INT NOT NULL
)
